# Generated by Django 5.2.1 on 2025-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=400)),
                ('project_image', models.ImageField(upload_to='')),
                ('project_description', models.TextField()),
                ('technologies', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
